# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: objective-c
cache: 
  - bundler
  - cocoapods
podfile: Example/Podfile
before_install:
  - bundle install
  - pod install --project-directory=Example --repo-update
script:
  - set -o pipefail && xcodebuild test -workspace Example/EasyReact.xcworkspace -scheme EasyReact-Example-Release -sdk iphonesimulator11.0 -destination 'platform=iOS Simulator,name=iPhone 6s Plus,OS=11.0' ONLY_ACTIVE_ARCH=YES | xcpretty
  - pod lib lint
after_success: 
  - bash <(curl -s https://codecov.io/bash)